query GetReviewTenant(
  $id: ID!
){
  tenantReview(id: $id){
   id
    comment
    score
    tenancyYears
    reviewer{
      id
      email
      firstName
      lastName
      fullName
      picture
      userType
      title
    }
    tenant{
      email
      phone
      firstName
      lastName
      userType
      picture
      tfaRequired
    }
    paymentSection{
      paysRent
      paysOnTime
      lateFrequency
      isLateJustified
      isLateCommunicated
    }
    leaseSection{
      compliesToTerms
      followsBuildingRules
      subletsWithoutPermission
      notifiesUpgrades
      disposesGarbageAppropriately
      notifiesHonestly
      terminatedEarly
      terminatedEarlyWithViableCause
    }
     maintenanceSection{
      reportsIssuesProperly
      makesLegitimateRequests
      doesThreatenManagement
      givesSufficientTime
      replicatesComplaints
      providesAccess
      cooperatesWithInstructions
      contactsManagementExcessively
      difficultyRating
    }
    complaintsSection{
      filesFormalComplaints
      contactsManagementFirst
      givesManagementSufficientTimeToFix
      historyOfFiling
      areComplaintsLegitimate
      providesAccess
    }
    damagesSection{
      damagesBuilding
      damagesUnit
      maintainsUnit
      exceededSecurityDeposit
    }
    behaviourSection{
      cooperates
      politenessRating
      isNoisy
      fightsWithTenants
      fightsWithStaff
    }
  }
}