query financialsGraphData($isPaid: Boolean){
  financialsGraphData(isPaid: $isPaid){
    totals{
      gross,
      incoming,
      outgoing
    }
    months{
    	edges{
        node{
          incoming
          outgoing
          month
        }
      }
    }
  }
}